import React from 'react';
import Footer from './includes/Footer';
import Header from './includes/Header';

const TermsAndConditions: React.FC = () => {
  return (
    <div>
    <Header/>
    <div className="p-6 max-w-3xl mx-auto text-black container">
      <h2 className="text-2xl font-bold mb-4">Terms and Conditions</h2>
      <p className="font-semibold mb-4"><strong>Version 1.1</strong></p>
      <p className="font-semibold mb-6"><strong>Last Updated: 15th February, 2024</strong></p>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">A. Introduction</h2>
        <p>
          This document is an electronic record and published in accordance with the provisions of the Information Technology Act 2000 and the rules thereunder and generated by a computer system and does not require any physical or digital signatures.
        </p>
        <p>
          The website <a href="https://nbitez.in/" target="_blank" rel="noopener noreferrer" className=" text-black hover:underline">https://nbitez.in/</a> (Website) and mobile application ‘Nbitez’ (App) (Website and App collectively referred to as the “Platform”) is operated and managed by the Company. The term Company shall collectively and individually refer to each company which operates and manages the Platform for undertaking retail business with respect to the respective cities.
        </p>
        <p>
          You can access the complete Company details here.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">B. General Terms</h2>
        <p>
          These terms of use, or "Terms," regulate how you use the Platform. The Company may also be referred to in these Terms as "Nbitez," "We," "Us," or "Our," depending on the situation, and users of the Platform are referred to as "You," "Your," or "User."
        </p>
        <p>
          We are grateful for your faith in us. We uphold appropriate security standards in order to protect Your information and the transactions.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">C. Acceptance of Terms</h2>
        <p>
          Before using the Platform, please carefully read these Terms. You must remove the App and may not use the Products and Services (as defined below) on the Platform if You disagree with these Terms. You enter into a legally binding agreement with Nbitez simply by using or accessing the Platform.
        </p>
        <p>
          By doing so, You agree to be bound by these Terms and all other Nbitez policies (such as the Company's cancellation and refund policy and its published privacy policy, or "Privacy Policy"), as posted on the Platform and updated from time to time. These terms go into effect on the date that You use the Platform. Additionally, by providing Your personal data, You accept that Nbitez may access Your personal information for the purpose of providing supplies.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">D. Changes to Terms</h2>
        <p>
          Nbitez is free to change or amend these Terms at any time. By using the "Last Updated" legend above, you can find out when these Terms were last updated. The most recent version of these Terms is always available on the Platform. You ought to go over the Platform's Terms on a frequent basis. You agree to these modifications if you keep using and accessing the Platform. Should You find that the amended Terms are unacceptable, You ought to stop using the Platform.
        </p>
      </section>

      {/* New Section: Products and Services */}
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">1. Products and Services</h2>
        
        <h3 className="text-lg font-semibold mb-2">1.1. Product/Service Availability</h3>
        <p>
          You agree that the Platform enables You to buy/get the following Products/Services:
        </p>
        <p>
          1.1.1. You are granted a personal, limited, non-exclusive, non-transferable, and revocable privilege to access and use the Platform for the purpose of buying certain products from the Company, which are sold on a business-to-consumer (B2C) basis for personal consumption only and not for resale. These products include grocery items, pharmaceuticals products (collectively, "Product(s)"). Without the purchase of Products on Platform, the Company does not offer services such product handling, last-mile delivery, including late-night delivery, and other services (collectively, "Services"), and a fee may be assessed for the same.
        </p>
        <p>
          1.1.2. Using the Platform to quickly and effectively address any questions or concerns you may have about Your Account and the goods you have obtained.
        </p>

        <h3 className="text-lg font-semibold mb-2">1.2. Restrictions on Resale and Modifications</h3>
        <p>
          The aforementioned revocable access right does not, in any way, include or authorize the resale of the Platform or its Content (as defined below) for commercial purposes. Any of the above-mentioned Products and/or Services may be added, changed, or removed by the Company at any time and without prior notice. In addition to these Terms, the Company may, in its sole discretion, establish terms and conditions that are particular to any category or area of Products. Your purchase of any such category or section of Products will be subject to these additional terms and conditions.
        </p>
        <p>
          The company maintains the right to deliver the materials to any location or city in India, as it sees fit, at its sole discretion. Please confirm that the supplies are accessible in your area or city before registering or applying to get any of the supplies. The company handles its own last-mile product delivery by using outside companies that offer pick-up and delivery services.
        </p>

        <h3 className="text-lg font-semibold mb-2">1.3. Company’s Responsibilities</h3>
        <p>
          The Company does not:
        </p>
        <ul className="list-inside list-disc">
          <li>(i) engage in any "unfair trade practices" regarding the Products and Services on the Platform or elsewhere;</li>
          <li>(ii) discriminate against Users who belong to the same class or classify Users arbitrarily; or</li>
          <li>(iii) discriminate against third-party delivery service providers.</li>
        </ul>
      </section>

      {/* New Section: Suitability for Usage */}
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">2. Suitability for Usage</h2>

        <h3 className="text-lg font-semibold mb-2">2.1. Age and Legal Competence</h3>
        <p>
          Unless otherwise specified below, the supplies are not available to minors, that is, individuals under the age of eighteen (18) years, undischarged insolvent, or any Users who are not competent to enter into a contract under the Indian Contract Act, 1872. By signing this, You attest that You are: 
        </p>
        <ul className="list-inside list-disc">
          <li>(i) of legal age to form a legally binding contract;</li>
          <li>(ii) not a person prohibited by relevant law from obtaining the supplies from the Platform; and</li>
          <li>(iii) competent to enter into a legally binding contract.</li>
        </ul>
        <p>
          If you are younger than 18, You may only access and use the Platform with a parent or guardian's explicit permission and under their supervision.
        </p>

        <h3 className="text-lg font-semibold mb-2">2.2. Discrimination</h3>
        <p>
          You will not treat third-party delivery service providers unfairly on the basis of age, marital status, sexual orientation, sex, religion, caste, creed, national origin, disability, or any other criterion that is thought to be illegal under the relevant laws. You will become ineligible and have your access to the Platform suspended if there is any reliable evidence of such discrimination, including any refusal to receive supplies based on the aforementioned metrics alone or in combination with any other measure.
        </p>
        <p>
          You won't be entitled to any compensation, and we won't be liable for any suspension that is implemented as a result of the previously mentioned incident.
        </p>
      </section>

      <h2 className="text-3xl font-semibold mb-6">Security, Password, and User Account</h2>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">3.1 Account</h2>
  <p className="text-base leading-relaxed">
    You must register and create an account on the Platform by entering any information that may be needed in accordance with the Privacy Policy ("Account") in order to access the supplies on the Platform.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">3.2 Responsibility for Account Information</h2>
  <p className="text-base leading-relaxed">
    All responsibility for the data You give Us rests with You. It is your responsibility to make sure that all of the information you submit, including the Account information, is accurate, current, and complete. You must quickly update Your Account information on the Platform or ask Nbitez to amend or revise any information if there is a change in the Account information or if any information is discovered to be inaccurate or incomplete. Nbitez reserves the right to refuse any and all supplies if the information you provide is false, inaccurate, unauthorized, out of date, or incomplete (or becomes false, inaccurate, out of date, or incomplete), or if Nbitez has reasonable grounds to suspect that the information is false, inaccurate, unauthorized, out of date, or incomplete. In the event that You fail to abide by the Terms as stated above or to comply with applicable laws, including those pertaining to the consumption of Nbitez, Nbitez expressly retains the right to deny You access to the Platform at any time and without notice.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">3.3 Responsibility for Account Activities</h2>
  <p className="text-base leading-relaxed">
    You bear complete responsibility for all activities that occur on Your Account and for maintaining the confidentiality of the information you supply about it. You pledge to alert Nbitez right away if you discover any unauthorized access to Your Account. If You fail to maintain Your Account details private and confidential, You may be held accountable for damages for losses resulting from unauthorized use of Your Account.
  </p>
</section>

<h2 className="text-3xl font-semibold mt-12 mb-6">Information Pertaining to Payments</h2>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">4.1 Payment Methods</h2>
  <p className="text-base leading-relaxed">
    Throughout the purchasing process, details about the approved payment methods on the Platform will be shown.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">4.2 Third-Party Payment Processors</h2>
  <p className="text-base leading-relaxed">
    You understand and agree that the Company may engage certain third-party vendors and service providers, including payment gateways, to process payments and manage payment card information, to the extent allowed by applicable law and pursuant to the Privacy Policy. The Company is able to guarantee that these outside suppliers and service providers have the required licenses from the relevant authorities.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">4.3 Valid Payment Details</h2>
  <p className="text-base leading-relaxed">
    To receive the supplies, you must supply valid bank or payment details ("Payment Details"). By providing the Payment Details, You represent, warrant, and covenant that: (a) You are legally authorized to provide such Payment Details; (b) You are legally authorized to make payments using such Payment Details; and (c) Your actions do not violate the terms and conditions governing Your use of such Payment Details or applicable law. The Platform allows you to add, delete, and amend the Payment Details you have provided at any time.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">4.4 Payment Issues</h2>
  <p className="text-base leading-relaxed">
    The Company is not accountable for payments made through the Platform using Your Payment Details, unless otherwise required by law. Specifically, the Company is not liable for any payments that do not complete because: (a) your bank account or any other payment did not contain sufficient funds to complete the transaction; (b) you have not provided the Company with correct Payment Details; (c) your payment card has expired; or (d) circumstances beyond the Company's reasonable control (such as, but not limited to, power outages, interruptions of cellular service, or any other interferences from an outside).
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">4.5 Unauthorized Transactions</h2>
  <p className="text-base leading-relaxed">
    The Company is not responsible for any unauthorized transactions made on the Platform using Your Payment Details. In such cases, the Company is under no obligation to repay your money.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">4.6 Payment Facility</h2>
  <p className="text-base leading-relaxed">
    The Company's payment facility is not a banking or financial service, but rather an automated online payment system that accepts payment on delivery for transactions on the Platform through authorized banking infrastructure and card payment gateway networks, as applicable. For some payment methods, Your issuer may charge You costs, such as transaction fees or other fees, for the completion of Your transaction.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">4.7 Nbitez Wallet</h2>
  <p className="text-base leading-relaxed">
    Nbitez Wallet: The Company offers a Wallet ("Nbitez Wallet") as a payment alternative for users to purchase supplies on the Platform. You agree that your use of Nbitez Wallet is subject to any geographical or other usage limits that may be imposed from time to time, as well as the extra terms and conditions.
  </p>
</section>


<h2 className="text-3xl font-semibold mb-6">Product Prices</h2>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">5.1 Ownership of Products</h2>
  <p className="text-base leading-relaxed">
    You become the owner of the Products once they are delivered to the address/location you specify.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">5.2 Product Pricing</h2>
  <p className="text-base leading-relaxed">
    Product pricing may vary based on variables, therefore please verify the Platform before placing an order. By placing an order, you agree to pay the prices specified. Unless otherwise noted, all products offered on the Platform shall be sold in Indian rupees, either at the Maximum Retail Price (MRP) (including of all taxes) or at a discounted price. The prices of the products may change from time to time. The Company strives to make Products available on the Platform at the best feasible prices. There may be an accidental error in the Prices and other Product details. You may notify us of any inaccuracies, and we will make the appropriate repairs.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">5.3 Charges and Fees</h2>
  <p className="text-base leading-relaxed">
    Users shall be informed of any charges, fees, or costs (including delivery fees) associated with purchasing Products on the Platform during the checkout process. The Company does not manipulate the prices of any Products available through the Platform.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">5.4 Lowest Prices in 10 Minutes</h2>
  <p className="text-base leading-relaxed">
    The term 'Lowest Prices in 10 Minutes' refers to the average price of all products provided for sale by the Company on the Platform, compared to rivals in the rapid commerce market for groceries. The Company expressly disclaims any liability arising from the individual products sold on the Platform.
  </p>
</section>

<h2 className="text-3xl font-semibold mt-12 mb-6">Delivery Details, Including Fees and Times</h2>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">6.1 Delivery Services</h2>
  <p className="text-base leading-relaxed">
    Last mile delivery services are included with product purchases on the Platform. The Company will deliver the Products purchased by You within the time frame specified on the Platform. The Company makes every effort to display an estimated delivery time for each order; however, the Company does not guarantee delivery within the stated time, as the exact delivery time of each order may vary due to a variety of factors such as the availability of third-party delivery service providers, demand, traffic and weather conditions, a force majeure event, and so on. You can also check the estimated time of arrival (ETA) when you go to the App's site before placing an order, to ensure that you are informed of the ETA before proceeding with the order. You agree that the Company reserves the right to charge You a fee for rain, peak hours and/or very high demand, late night fee, packing handling charges, convenience/platform fee, small cart fee and any other fee in addition to the delivery fee for order delivery, as shown on the view bill section before the check out page on the App.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">6.2 Delivery Address</h2>
  <p className="text-base leading-relaxed">
    The Products will be delivered to the address you mentioned when placing the order on the Platform. You are solely responsible for supplying an accurate and full delivery address, as well as any other delivery instructions. The Company shall not be liable for any delay in delivering the order placed by You on the Platform caused by the erroneous or incomplete address given by You.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">6.3 Delivery to Unattended Locations</h2>
  <p className="text-base leading-relaxed">
    The items will normally be delivered when an appropriate person is able to receive the order at the address You gave. If you request that a delivery be left unattended at your address, you expressly release the Company from any and all obligations that may arise as a result of the Products being left unattended for an extended period. This includes, but is not limited to, theft, tampering, contamination, and any changes in temperature of things that must be maintained refrigerated or frozen.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">6.4 Cash on Delivery (CoD)</h2>
  <p className="text-base leading-relaxed">
    If you choose 'Cash on Delivery (CoD)' payment mode, the Company reserves the right to refuse delivery of the ordered Products if you fail to make the full payment. The Company will treat such an order as canceled and will not be liable for any losses or damage that may arise as a result of such non-delivery. The Company reserves the right to charge You the delivery price and any other fees for such canceled order and reclaim the same in its sole discretion to repay the costs spent during such delivery attempt.
  </p>
</section>

<h2 className="text-3xl font-semibold mt-12 mb-6">Returns, Cancellations, and Refunds</h2>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">7.1 Returns</h2>
  <p className="text-base leading-relaxed">
    You may return the Product in an order under the following conditions:
  </p>
  <ul className="list-disc pl-6">
    <li>Incorrect item delivered;</li>
    <li>Damaged or degraded items upon delivery. You undertake to provide Us with any necessary proofs, including but not limited to pictures of products with faults.</li>
  </ul>

  <p className="text-base leading-relaxed mt-4">
    You must inspect the Products upon delivery and conduct an exchange or refund with the necessary proofs on the Platform. You can swap or return the product by contacting our customer service department. IT IS HEREBY SPECIFIED THAT NO EXCHANGES OR RETURNS WILL BE ACCEPTED IF THE PRODUCT PACKAGING IS OPENED OR THE PRODUCT IS USED/CONSUMED IN PART OR WHOLE.
  </p>

  <p className="text-base leading-relaxed mt-4">
    You may exchange or return Products purchased from Us as long as they are sealed/unopened/unused, in their original condition, and returned on the same day of delivery. Please keep in mind that requests for exchanges or returns will no longer be allowed beginning the day after We delivered the Product/s to You. We may request that you dispose of the Products for which we have completed a refund.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">7.2 Cancellations</h2>
  <p className="text-base leading-relaxed">
    You can cancel your order free of charge before the Company accepts it. After the Company accepts your order, you cannot cancel it. The Company may cancel an order (in whole or in part) for a variety of reasons, including product shortages or unavailability, as well as force majeure circumstances. If the Company cancels an order, You will not be charged for the cancellation, and the Company will return any payments you have paid.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">7.3 Refunds</h2>
  <p className="text-base leading-relaxed">
    Please be advised that if You choose to cancel or return the Products, the refund amount for those Products that are eligible for return under these Terms will be processed within seven (7) business days of us verifying and confirming the refund request. Your reimbursement will be granted only when the conditions specified by Us are met. The refund amount will be credited to the source account or the Nbitez Wallet, as you choose. You acknowledge that after initiating the refund, it may take additional time for Your return to reflect in Your account, which is subject to the terms and conditions of Your financial institution or payment gateway service provider.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">7.4 Additional Conditions</h2>
  <p className="text-base leading-relaxed">
    The terms for returns, cancellations, and refunds are subject to reasonable additional conditions and will be communicated to the User via push notifications on the Platform or other means as specified in these Terms or as determined by the Company.
  </p>
</section>


<h2 className="text-3xl font-semibold mb-6">User Care</h2>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">8.1 Manufacturer's Warranty and Guarantee</h2>
  <p className="text-base leading-relaxed">
    The manufacturer's warranty and guarantee apply to the Products. You can contact the manufacturer directly using the contact information provided on the packaging. The Company is only a reseller and assumes no responsibility for the manufacturing faults, quality, taste, or performance of the Products sold.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">8.2 Product Images and Labels</h2>
  <p className="text-base leading-relaxed">
    You agree and understand that the Product images are a representation of the Product and not the actual image of the Product sold to You, and that you must read the physical product label for the calorific and nutrition value, using instructions, batch, manufacture date, content, weight, manufacturer, and customer care details, as applicable, before consuming the Products. While every reasonable effort is made to ensure the accuracy of the information on the platform, actual product packaging may contain more and/or different information than what is shown on the platform. It is recommended that you refer to the information presented on the actual product packaging.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">8.3 Transaction Rejection</h2>
  <p className="text-base leading-relaxed">
    The Company reserves the right to refuse to process transactions by Users who have a prior history of questionable transactions, including, but not limited to, breach of any agreements with the Company, breach/violation of any law, bank charges, or breach of any policy, without providing reasons. The Company may conduct such checks as it deems necessary before approving the User's order for security or other reasons at its discretion. As a result of such inspections, if the Company is not pleased with the User's reliability or the authenticity of the transaction, it reserves the right to reject the order. To preserve transaction security, the Company may postpone or cancel any transaction at its sole discretion if it suspects any User's authenticity or behavior, or if the User conducts excessive transaction volumes.
  </p>
</section>

<h2 className="text-3xl font-semibold mt-12 mb-6">Beware of Fraud</h2>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">8.4.1 Fraud Awareness</h2>
  <p className="text-base leading-relaxed">
    Do not give sensitive information, such as debit/credit card numbers, CVV numbers, OTPs, UPI/ATM pins, with anybody pretending to be a Company representative. The Company or its authorized agents will never ask you to divulge the aforementioned information. Report any incidents of fraud to your bank, the nearest police station, or https://cybercrime.gov.in/.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">8.4.2 Help with Nbitez Orders</h2>
  <p className="text-base leading-relaxed">
    To get help with a Nbitez order or refund, go to the 'Get Help' option of the App.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">8.4.3 Fraudulent Links and Calls</h2>
  <p className="text-base leading-relaxed">
    Be cautious when clicking on links claiming to be Nbitez or a lookalike, sharing payment links on social media, or receiving calls from unknown numbers requesting personal or financial information.
  </p>
</section>

<h2 className="text-3xl font-semibold mt-12 mb-6">Use of Platform</h2>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">9.1 Platform Access</h2>
  <p className="text-base leading-relaxed">
    Subject to compliance with the Terms, the Company now grants You a personal, non-exclusive, non-transferable, restricted, and revocable right to access and use the Platform. You undertake to use the Platform only for the following purposes: (a) as permitted by the Terms; (b) in accordance with any applicable law, regulation, or generally accepted practices or standards; and (c) to get supplies via the Platform. You agree not to engage in any activity that may have a harmful effect on the Company's and/or other Users' use of the Platform.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">9.2 Restrictions on Platform Use</h2>
  <p className="text-base leading-relaxed">
    You undertake not to replicate, duplicate, copy, sell, resell, or exploit any component of the Platform for commercial reasons.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">9.3 Trademarks and Logos</h2>
  <p className="text-base leading-relaxed">
    You agree not to use framing techniques to surround the Platform's trademarks, logos, or other proprietary material.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">9.4 Automated Access</h2>
  <p className="text-base leading-relaxed">
    You agree to use the Platform only through the interface provided by the Company. You may not use any deep-link, robot, spider, or other automatic device, programme, algorithm, or methodology, or any similar or equivalent manual process, to access, acquire, copy, or monitor any portion of the Platform or Content, or in any way reproduce or circumvent the navigational structure or presentation of the Platform, materials, or any Content, to obtain or attempt to obtain any materials, documents, or information through any means not specifically made available.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">9.5 Restrictions on Material</h2>
  <p className="text-base leading-relaxed">
    You agree not to host, display, upload, change, publish, transmit, save, update, or share material that:
  </p>
  <ul className="list-disc pl-6">
    <li>Belongs to someone else and is not the User's property.</li>
    <li>Is defamatory, obscene, pornographic, paedophilic, invasive of another's privacy, insulting or harassing on the basis of gender, libellous, racially, or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with the laws in force.</li>
    <li>Is detrimental to children.</li>
    <li>Violates any patent, trademark, copyright, or other proprietary rights.</li>
    <li>Violates any current laws.</li>
    <li>Impersonates another person.</li>
    <li>Endangers India's unity, integrity, defence, security, or sovereignty, harms friendly relations with foreign states, disrupts public order, incites crime, obstructs investigation, or insults other nations.</li>
    <li>Contains software viruses or any other computer code, file or programme designed to interrupt, destroy, or limit the functionality of any computer resource.</li>
    <li>Is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity, or agency for financial gain or to cause any injury to any person.</li>
    <li>Do not disrupt or harm the security of the Platform, systems resources, accounts, passwords, servers, or networks connected to or accessible through the Platform or any affiliated or linked sites.</li>
    <li>Do not violate the Terms contained herein or elsewhere.</li>
    <li>Do not reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information.</li>
  </ul>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">9.6 Responsibility for Equipment</h2>
  <p className="text-base leading-relaxed">
    You are solely responsible for maintaining computer equipment, devices, and internet connections needed to access, use, and transact on the platform.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">9.7 Exposure to Offensive Content</h2>
  <p className="text-base leading-relaxed">
    You accept that using the Platform or its suppliers may expose you to content that some users may find offensive, indecent, or objectionable. This content may or may not be identified as such. You agree to use the Platform and any supplies at your own risk, and to the fullest extent permitted by applicable law. The Company will not be liable to You for any Content that You find offensive, obscene, or objectionable.
  </p>
</section>

<h2 className="text-3xl font-semibold mt-12 mb-6">Intellectual Property Rights</h2>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">10.1 Platform Content</h2>
  <p className="text-base leading-relaxed">
    The Platform and its processes, including text, videos, graphics, user interfaces, visual interfaces, sounds and music (if any), artwork, and computer code (and any combinations thereof) (collectively, the "Content") on the Platform are licenced to the Company. The design, structure, selection, coordination, expression, look and feel, and arrangement of such Content is protected by copyright and patent.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">10.2 Trademarks and Marks</h2>
  <p className="text-base leading-relaxed">
    The Platform's trademarks, logos, and service marks ("Marks") are either licenced by the Company or owned by third parties. You are not entitled to use the Marks without the previous authorization of the Company or the relevant third party (the Marks' owner), as applicable. Access or use of the Platform does not grant any party the right to utilise trademarks, logos, or other marks in any way.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">10.3 Products Intellectual Property</h2>
  <p className="text-base leading-relaxed">
    The Company does not claim ownership of any intellectual property rights related to the Products.
  </p>
</section>

<section className="mb-8">
  <h2 className="text-xl font-medium mb-4">10.4 Third-Party References</h2>
  <p className="text-base leading-relaxed">
    References to third-party names, marks, services, or goods on the Platform are provided with their express consent for your convenience and do not imply endorsement, sponsorship, or recommendation.
  </p>
</section>


    </div>
    <Footer/>
    </div>
  );
};

export default TermsAndConditions;
